### ISSUE TITLE
有错误

### ISSUE THREAD

**Issue by cobola** [SunGg12138/node-qiniu-sdk#6]
TypeError [ERR_INVALID_ARG_TYPE]: The "msecs" argument must be of type number. Received type object

按照给的最简单的例子跑的  求助

**Comment by SunGg12138** [comment]
哪个接口  什么参数呀

**Comment by cobola** [comment]
![image](https://user-images.githubusercontent.com/4435875/51222333-440d4100-1978-11e9-9d41-b287675351f4.png)
```
  const bucket = qiniu.bucket('node2d-file')
  let d = await bucket.domain()
  log.info(d)

```

**Comment by SunGg12138** [comment]
你报的错误应该不是node-qiniu-sdk模块的错误：
你应该看一下你项目的文件：
![_48ddd234-ef2d-481e-943a-1ba5bbd18cf7](https://user-images.githubusercontent.com/16427275/51224238-f3014b00-197f-11e9-9cbb-36bf0f1580c2.png)

**Comment by cobola** [comment]
```

(node:16538) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "msecs" argument must be of type number. Received type object
    at validateNumber (internal/validators.js:130:11)
    at validateTimerDuration (internal/timers.js:146:3)
    at Socket.setTimeout (net.js:418:11)
    at setRequestSocket (_http_agent.js:361:10)
    at handleSocketCreation_Inner (_http_agent.js:349:7)
    at oncreate (_http_agent.js:224:5)
    at Agent.createSocket (_http_agent.js:229:5)
    at Agent.addRequest (_http_agent.js:185:10)
    at new ClientRequest (_http_client.js:249:16)
    at Object.request (http.js:42:10)
    at request (/Users/cobola/server/node_modules/node-request-slim/index.js:106:26)
    at Promise (/Users/cobola/server/node_modules/node-qiniu-sdk/lib/request/index.js:6:5)
    at new Promise (<anonymous>)
    at module.exports (/Users/cobola/server/node_modules/node-qiniu-sdk/lib/request/index.js:5:10)
    at SDK.rs (/Users/cobola/server/node_modules/node-qiniu-sdk/index.js:415:10)
    at Bucket.domain (/Users/cobola/server/node_modules/node-qiniu-sdk/lib/bucket.js:88:19)
    at testQn (/Users/cobola/server/test/test.js:14:24)
    at Object.<anonymous> (/Users/cobola/server/test/test.js:23:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
(node:16538) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

这是详细的报错内容 我node的版本是 v10.15.0

**Comment by cobola** [comment]
搞定 多谢
